services:
  database:
    container_name: db-pgsql-6392c
    image: postgres:17.4

    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tododb

    networks:
      - my_network
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U docker -d tododb'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    container_name: backend-6392c
    build: ./backend/

    networks:
      - my_network
    expose:
      - "8120"
    ports:
      - "8120:8120"
    depends_on:
      database:
        condition: service_healthy
        restart: true

  frontend:
    container_name: frontend-6392c
    build: ./frontend/

    networks:
      - my_network
    ports:
      - "8122:8122"




networks:
  my_network:

volumes:
  postgresql_data:
