version: "3.8"

services:
    backend:
        container_name: backend

        build: ./backend/

        networks:
            - my_network

        ports:
            - "8120:8120"


    frontend:
        container_name: frontend

        build: ./frontend/

        networks:
            - my_network

        ports:
            - "8122:8122"

    database:
        container_name: db-postgres
        
        image: postgres

        environment:
            POSTGRES_BD: tododb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

        ports:
            - "5432:5432"

        volumes:
        - pg_data:/var/lib/postgresql/data

networks:
    my_network:

volumes:
    pg_data:
